spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://localhost:9411/
  application:
    name: trace-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    enable: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


sample:
  zipkin:
    enabled: true